# Generated by Django 6.0.5 on 2026-06-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverificationcode',
            name='purpose',
            field=models.CharField(choices=[('reset_password', 'Reset Password'), ('change_email', 'Change Email'), ('registration', 'Registration')], max_length=20),
        ),
    ]
