# Generated by Django 6.0.4 on 2026-06-02 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rescue", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdoptApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "online_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("need_material", "Need Material"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("audit_opinion", models.TextField(blank=True, null=True)),
                ("audited_at", models.DateTimeField(blank=True, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adopt_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "auditor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audited_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "adopt_application",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdoptAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_type", models.CharField(max_length=30)),
                ("file_url", models.CharField(max_length=500)),
                ("file_size", models.IntegerField()),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="pets.adoptapplication",
                    ),
                ),
            ],
            options={
                "db_table": "adopt_attachment",
            },
        ),
        migrations.CreateModel(
            name="AdoptOfflineVerify",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verify_status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("verify_note", models.TextField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_verify",
                        to="pets.adoptapplication",
                    ),
                ),
                (
                    "verifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="offline_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "adopt_offline_verify",
            },
        ),
        migrations.CreateModel(
            name="AdoptQuestionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answers_json", models.JSONField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaire",
                        to="pets.adoptapplication",
                    ),
                ),
            ],
            options={
                "db_table": "adopt_questionnaire",
            },
        ),
        migrations.CreateModel(
            name="PetProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("species", models.CharField(max_length=50)),
                ("breed", models.CharField(blank=True, max_length=100, null=True)),
                ("age_months", models.IntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "health_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("photo_url", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "adoption_status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("pending", "Pending"),
                            ("adopted", "Adopted"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rescue_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pets",
                        to="rescue.rescuecase",
                    ),
                ),
            ],
            options={
                "db_table": "pet_profile",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="adoptapplication",
            name="pet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="applications",
                to="pets.petprofile",
            ),
        ),
    ]
