# Generated by Django 6.0.6 on 2026-06-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='size_category',
            field=models.CharField(blank=True, choices=[('small', '小型犬'), ('medium', '中型犬'), ('large', '大型犬')], max_length=10, null=True),
        ),
    ]
