# Generated by Django 6.0.6 on 2026-06-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_petprofile_size_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petprofile',
            name='size_category',
            field=models.CharField(blank=True, choices=[('small', '小型'), ('medium', '中型'), ('large', '大型')], max_length=10, null=True),
        ),
    ]
