# Generated by Django 6.0.4 on 2026-06-02 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CmsCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "Disabled"), (1, "Enabled")], default=1
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "cms_category",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="CmsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "article_type",
                    models.CharField(
                        choices=[
                            ("science", "Science"),
                            ("announcement", "Announcement"),
                            ("law", "Law"),
                            ("rescue_case", "Rescue Case"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.CharField(blank=True, max_length=500, null=True)),
                ("content", models.TextField()),
                ("cover_url", models.CharField(blank=True, max_length=500, null=True)),
                ("view_count", models.IntegerField(default=0)),
                ("is_pinned", models.BooleanField(default=False)),
                ("sort_weight", models.IntegerField(default=0)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "Draft"), (1, "Published"), (2, "Offline")],
                        default=0,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="cms_articles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="cms.cmscategory",
                    ),
                ),
            ],
            options={
                "db_table": "cms_article",
                "ordering": [
                    "-is_pinned",
                    "-sort_weight",
                    "-published_at",
                    "-created_at",
                ],
            },
        ),
    ]
