# Generated by Django 6.0.4 on 2026-06-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GalleryImage",
        ),
    ]
