# Generated by Django 6.0.4 on 2026-06-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0002_delete_gallery_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentmoderation",
            name="target_summary",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="contentmoderation",
            name="action",
            field=models.CharField(
                choices=[
                    ("approve", "Approve"),
                    ("hide", "Hide"),
                    ("delete", "Delete"),
                    ("ban", "Ban"),
                ],
                max_length=20,
            ),
        ),
    ]
