# Generated by Django 6.0.4 on 2026-06-02 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RescueCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rescue_no", models.CharField(max_length=32, unique=True)),
                (
                    "discover_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "discover_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "discover_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("appearance", models.TextField(blank=True, null=True)),
                ("health_note", models.TextField(blank=True, null=True)),
                ("photo_urls", models.JSONField(blank=True, default=list)),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("pending_rescue", "Pending Rescue"),
                            ("in_medical", "In Medical"),
                            ("recovering", "Recovering"),
                            ("awaiting_adoption", "Awaiting Adoption"),
                            ("rescued", "Rescued"),
                            ("abandoned", "Abandoned"),
                        ],
                        default="pending_rescue",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="rescue_cases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "rescue_case",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RescueStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=20, null=True)),
                ("to_status", models.CharField(max_length=20)),
                ("remark", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="rescue_status_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rescue_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="rescue.rescuecase",
                    ),
                ),
            ],
            options={
                "db_table": "rescue_status_log",
                "ordering": ["created_at"],
            },
        ),
    ]
