# Generated by Django 6.0.6 on 2026-06-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0002_discover_location_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescuecase',
            name='afraid_of_people',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rescuecase',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rescuecase',
            name='health_status',
            field=models.CharField(blank=True, choices=[('healthy', '健康'), ('minor_injury', '轻微伤病'), ('severe_injury', '严重伤病')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='rescuecase',
            name='is_injured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rescuecase',
            name='nickname',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rescuecase',
            name='size_category',
            field=models.CharField(blank=True, choices=[('small', '小型'), ('medium', '中型'), ('large', '大型')], default='', max_length=20),
        ),
    ]
