# Generated by Django 6.0.6 on 2026-06-14 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0003_rescuecase_afraid_of_people_rescuecase_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rescuecase',
            name='help_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rescuecase',
            name='helpers',
            field=models.ManyToManyField(blank=True, related_name='helped_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
