# Generated by Django 6.0.6 on 2026-06-14 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0004_rescuecase_help_date_rescuecase_helpers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RescueStageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rescue_stage_records', to=settings.AUTH_USER_MODEL)),
                ('rescue_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_records', to='rescue.rescuecase')),
            ],
            options={
                'db_table': 'rescue_stage_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
